// This file is generated by Slice Machine. Update with care!

import Alert from './Alert';
import ContactForm from './ContactForm';
import Image from './Image';
import Quote from './Quote';
import Text from './Text';

export {
	Alert,
	ContactForm,
	Image,
	Quote,
	Text,
};

export const components = {
	alert: Alert,
	contact_form: ContactForm,
	image: Image,
	quote: Quote,
	text: Text,
};
